# Generated by Django 4.1.4 on 2023-01-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1996-04-29'),
            preserve_default=False,
        ),
    ]
